id: PB454EDC1
initial_creation_type: ocr
source_metadata:
  volumes:
    152e0c7e69f543c7b73dc1e9c9c06dea:
      base_file: v050.txt
      image_group_id: I1PD95895
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1666
      volume_number: 50
