id: PB454EDC1
initial_creation_type: ocr
source_metadata:
  volumes:
    bb8949bf761e4a6984fac3a16e14fa62:
      base_file: v050.txt
      image_group_id: I1PD95895
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1666
      volume_number: 50
