id: D9818EAA3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-18T07:01:13+00:00'
last_modified: '2022-05-27T04:22:27.084034+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e6f6:
      image_group_id: I1PD95895
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1666
      order: 50
      base_file: e6f6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
